name: Build

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'

    steps:
    - uses: 'actions/checkout@v3'

    - name: 'build'
      run: docker build .

