name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'    

    - name: 'configure docker'
      run: gcloud auth configure-docker

    - name: 'build'
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_PROJECT_NAME }}:latest .

    - name: 'push'
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_PROJECT_NAME }}:latest

    - name: 'deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: '${{ secrets.GCP_PROJECT_NAME }}'
        image: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_PROJECT_NAME }}:latest
        region: '${{ secrets.GCP_REGION }}'

