name: Lint

on:
  pull_request: []
  push:
    branches-ignore:
      - 'main'
permissions:
  contents: read # Required for actions/checkout@v3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: npm run lint
